version: 2.1
orbs:
  ruby: circleci/ruby@1.8.0
  node: circleci/node@5.0.2

jobs:
  build:
    docker:
      - image: circleci/ruby:2.5.3
      - image: circleci/node:16.13.1
    working_directory: ~/end-of-the-tower
    steps:
      - checkout:
          path: ~/end-of-the-tower
      - ruby/install-deps:
          path: ./api/vendor/bundle
      - node/install-packages:
          cache-path: ~/end-of-the-tower/client/node_modules
          override-ci-command: npm install

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      # - test:
      #   requires:
      #     - build
