version: 2.1
orbs:
  ruby: circleci/ruby@1.8.0
  node: circleci/node@5.0.2

jobs:
  api_build:
    working_directory: ~/end-of-the-tower/api
    docker:
      - image: circleci/ruby:2.5.3
    steps:
      - checkout:
          path: ~/end-of-the-tower
      - ruby/install-deps

  client_build:
    working_directory: ~/end-of-the-tower/client
    docker:
      - image: circleci/node:16.13.1
    steps:
      - checkout:
          path: ~/end-of-the-tower
      - node/install-packages:
          cache-path: ~/end-of-the-tower/client/node_modules
          override-ci-command: npm install

  api_test:
    working_directory: ~/end-of-the-tower/api
    docker:
      - image: circleci/ruby:2.5.3
      - image: circleci/mysql:5.5
        environment:
          MYSQL_DATABASE: end_of_the_tower_test
          MYSQL_USER: root
          MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
    environment:
      BUNDLE_JOBS: "3"
      BUNDLE_RETRY: "3"
      APP_DATABASE_HOST: "127.0.0.1"
      MYSQL_TEST_DATABASE: end_of_the_tower_test
      MYSQL_USER: root
      MYSQL_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      RAILS_ENV: test
    steps:
      - checkout:
          path: ~/end-of-the-tower
      - ruby/install-deps
      - run:
          name: Database setup
          command: bundle exec rails db:migrate
      - run:
          name: api test
          command: bundle exec rspec

workflows:
  version: 2
  build_and_test:
    jobs:
      - api_build
      - client_build:
          requires:
            - api_build
      - api_test:
          requires:
            - client_build
      # - client_test:
      #   requires:
      #     - api_test
